// See Ride.h
export enum RideType {
  SpiralRollerCoaster = 0,
  StandUpRollerCoaster,
  SuspendedSwingingCoaster,
  InvertedRollerCoaster,
  JuniorRollerCoaster,
  MiniatureRailway,
  Monorail,
  MiniSuspendedCoaster,
  BoatHire,
  WoodenWildMouse,
  Steeplechase = 10,
  CarRide,
  LaunchedFreefall,
  BobsleighCoaster,
  ObservationTower,
  LoopingRollerCoaster,
  DinghySlide,
  MineTrainCoaster,
  Chairlift,
  CorkscrewRollerCoaster,
  Maze = 20,
  SpiralSlide,
  GoKarts,
  LogFlume,
  RiverRapids,
  Dodgems,
  SwingingShip,
  SwingingInverterShip,
  FoodStall,
  Unknown1d,
  DrinkStall = 30,
  Unknown1f,
  Shop,
  MerryGoRound,
  Unknown22,
  InformationKiosk,
  Toilets,
  FerrisWheel,
  MotionSimulator,
  ThreeDCinema,
  TopSpin = 40,
  SpaceRings,
  ReverseFreefallCoaster,
  Lift,
  VerticalDropRollerCoaster,
  CashMachine,
  Twist,
  HauntedHouse,
  FirstAid,
  Circus,
  GhostTrain = 50,
  TwisterRollerCoaster,
  WoodenRollerCoaster,
  SideFrictionRollerCoaster,
  SteelWildMouse,
  MultiDimensionRollerCoaster,
  MultiDimensionRollerCoasterAlt,
  FlyingRollerCoaster,
  FlyingRollerCoasterAlt,
  VirginiaReel,
  SplashBoats = 60,
  MiniHelicopters,
  LayDownRollerCoaster,
  SuspendedMonorail,
  LayDownRollerCoasterAlt,
  ReverserRollerCoaster,
  HeartlineTwisterCoaster,
  MiniGolf,
  GigaCoaster,
  RotoDrop,
  FlyingSaucers = 70,
  CrookedHouse,
  MonorailCycles,
  CompactInvertedCoaster,
  WaterCoaster,
  AirPoweredVerticalCoaster,
  InvertedHairpinCoaster,
  MagicCarpet,
  SubmarineRide,
  RiverRafts,
  Unknown50 = 80,
  Enterprise,
  Unknown52,
  Unknown53,
  Unknown54,
  Unknown55,
  InvertedImpulseCoaster,
  MiniRollerCoaster,
  MineRide,
  Unknown59,
  LimLaunchedRollerCoaster = 90,
  Hypercoaster,
  HyperTwister,
  MonsterTrucks,
  SpinningWildMouse,
  ClassicMiniRollerCoaster,
  HybridCoaster,
  SingleRailRollerCoaster,
  AlpineCoaster,
  ClassicWoodenRollerCoaster,
  Count
}
